# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class EventBreakpointsCommand(StrEnum):
    SET_INSTRUMENTATION_BREAKPOINT = "EventBreakpoints.setInstrumentationBreakpoint"
    REMOVE_INSTRUMENTATION_BREAKPOINT = (
        "EventBreakpoints.removeInstrumentationBreakpoint"
    )
    DISABLE = "EventBreakpoints.disable"


class SetInstrumentationBreakpointParams(CDPModel):
    """
    Sets breakpoint on particular native event.
    """

    event_name: str


class RemoveInstrumentationBreakpointParams(CDPModel):
    """
    Removes breakpoint on particular native event.
    """

    event_name: str
