# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class TetheringCommand(StrEnum):
    BIND = "Tethering.bind"
    UNBIND = "Tethering.unbind"


class BindParams(CDPModel):
    """
    Request browser port binding.
    """

    port: int


class UnbindParams(CDPModel):
    """
    Request browser port unbinding.
    """

    port: int
