# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class SecurityCommand(StrEnum):
    DISABLE = "Security.disable"
    ENABLE = "Security.enable"
    SET_IGNORE_CERTIFICATE_ERRORS = "Security.setIgnoreCertificateErrors"
    HANDLE_CERTIFICATE_ERROR = "Security.handleCertificateError"
    SET_OVERRIDE_CERTIFICATE_ERRORS = "Security.setOverrideCertificateErrors"


class SetIgnoreCertificateErrorsParams(CDPModel):
    """
    Enable/disable whether all certificate errors should be ignored.
    """

    ignore: bool


class HandleCertificateErrorParams(CDPModel):
    """
    Handles a certificate error that fired a certificateError event.
    """

    event_id: int
    action: CertificateErrorAction


class SetOverrideCertificateErrorsParams(CDPModel):
    """
    Enable/disable overriding certificate errors. If enabled, all certificate error
    events need to be handled by the DevTools client and should be answered with
    `handleCertificateError` commands.
    """

    override: bool
