# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from cdpify.client import CDPClient

from .commands import (
    PageCommand,
    AddCompilationCacheParams,
    AddScriptToEvaluateOnLoadParams,
    AddScriptToEvaluateOnLoadResult,
    AddScriptToEvaluateOnNewDocumentParams,
    AddScriptToEvaluateOnNewDocumentResult,
    CaptureScreenshotParams,
    CaptureScreenshotResult,
    CaptureSnapshotParams,
    CaptureSnapshotResult,
    CreateIsolatedWorldParams,
    CreateIsolatedWorldResult,
    DeleteCookieParams,
    EnableParams,
    GenerateTestReportParams,
    GetAdScriptAncestryParams,
    GetAdScriptAncestryResult,
    GetAnnotatedPageContentParams,
    GetAnnotatedPageContentResult,
    GetAppIdResult,
    GetAppManifestParams,
    GetAppManifestResult,
    GetFrameTreeResult,
    GetInstallabilityErrorsResult,
    GetLayoutMetricsResult,
    GetManifestIconsResult,
    GetNavigationHistoryResult,
    GetOriginTrialsParams,
    GetOriginTrialsResult,
    GetPermissionsPolicyStateParams,
    GetPermissionsPolicyStateResult,
    GetResourceContentParams,
    GetResourceContentResult,
    GetResourceTreeResult,
    HandleJavaScriptDialogParams,
    NavigateParams,
    NavigateResult,
    NavigateToHistoryEntryParams,
    PrintToPDFParams,
    PrintToPDFResult,
    ProduceCompilationCacheParams,
    ReloadParams,
    RemoveScriptToEvaluateOnLoadParams,
    RemoveScriptToEvaluateOnNewDocumentParams,
    ScreencastFrameAckParams,
    SearchInResourceParams,
    SearchInResourceResult,
    SetAdBlockingEnabledParams,
    SetBypassCSPParams,
    SetDeviceMetricsOverrideParams,
    SetDeviceOrientationOverrideParams,
    SetDocumentContentParams,
    SetDownloadBehaviorParams,
    SetFontFamiliesParams,
    SetFontSizesParams,
    SetGeolocationOverrideParams,
    SetInterceptFileChooserDialogParams,
    SetLifecycleEventsEnabledParams,
    SetPrerenderingAllowedParams,
    SetRPHRegistrationModeParams,
    SetSPCTransactionModeParams,
    SetTouchEmulationEnabledParams,
    SetWebLifecycleStateParams,
    StartScreencastParams,
)

from .types import (
    CompilationCacheParams,
    FontFamilies,
    FontSizes,
    FrameId,
    ReferrerPolicy,
    ScriptFontFamilies,
    ScriptIdentifier,
    TransitionType,
    Viewport,
)


class PageClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def add_script_to_evaluate_on_load(
        self,
        *,
        script_source: str,
        session_id: str | None = None,
    ) -> AddScriptToEvaluateOnLoadResult:
        params = AddScriptToEvaluateOnLoadParams(scriptSource=script_source)

        result = await self._client.send_raw(
            method=PageCommand.ADD_SCRIPT_TO_EVALUATE_ON_LOAD,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return AddScriptToEvaluateOnLoadResult.model_validate(result)

    async def add_script_to_evaluate_on_new_document(
        self,
        *,
        source: str,
        world_name: str | None = None,
        include_command_line_a_p_i: bool | None = None,
        run_immediately: bool | None = None,
        session_id: str | None = None,
    ) -> AddScriptToEvaluateOnNewDocumentResult:
        params = AddScriptToEvaluateOnNewDocumentParams(
            source=source,
            worldName=world_name,
            includeCommandLineAPI=include_command_line_a_p_i,
            runImmediately=run_immediately,
        )

        result = await self._client.send_raw(
            method=PageCommand.ADD_SCRIPT_TO_EVALUATE_ON_NEW_DOCUMENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return AddScriptToEvaluateOnNewDocumentResult.model_validate(result)

    async def bring_to_front(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.BRING_TO_FRONT,
            params=None,
            session_id=session_id,
        )
        return result

    async def capture_screenshot(
        self,
        *,
        format: Literal["jpeg", "png", "webp"] | None = None,
        quality: int | None = None,
        clip: Viewport | None = None,
        from_surface: bool | None = None,
        capture_beyond_viewport: bool | None = None,
        optimize_for_speed: bool | None = None,
        session_id: str | None = None,
    ) -> CaptureScreenshotResult:
        params = CaptureScreenshotParams(
            format=format,
            quality=quality,
            clip=clip,
            fromSurface=from_surface,
            captureBeyondViewport=capture_beyond_viewport,
            optimizeForSpeed=optimize_for_speed,
        )

        result = await self._client.send_raw(
            method=PageCommand.CAPTURE_SCREENSHOT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return CaptureScreenshotResult.model_validate(result)

    async def capture_snapshot(
        self,
        *,
        format: Literal["mhtml"] | None = None,
        session_id: str | None = None,
    ) -> CaptureSnapshotResult:
        params = CaptureSnapshotParams(format=format)

        result = await self._client.send_raw(
            method=PageCommand.CAPTURE_SNAPSHOT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return CaptureSnapshotResult.model_validate(result)

    async def clear_device_metrics_override(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CLEAR_DEVICE_METRICS_OVERRIDE,
            params=None,
            session_id=session_id,
        )
        return result

    async def clear_device_orientation_override(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CLEAR_DEVICE_ORIENTATION_OVERRIDE,
            params=None,
            session_id=session_id,
        )
        return result

    async def clear_geolocation_override(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CLEAR_GEOLOCATION_OVERRIDE,
            params=None,
            session_id=session_id,
        )
        return result

    async def create_isolated_world(
        self,
        *,
        frame_id: FrameId,
        world_name: str | None = None,
        grant_univeral_access: bool | None = None,
        session_id: str | None = None,
    ) -> CreateIsolatedWorldResult:
        params = CreateIsolatedWorldParams(
            frameId=frame_id,
            worldName=world_name,
            grantUniveralAccess=grant_univeral_access,
        )

        result = await self._client.send_raw(
            method=PageCommand.CREATE_ISOLATED_WORLD,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return CreateIsolatedWorldResult.model_validate(result)

    async def delete_cookie(
        self,
        *,
        cookie_name: str,
        url: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = DeleteCookieParams(cookieName=cookie_name, url=url)

        result = await self._client.send_raw(
            method=PageCommand.DELETE_COOKIE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        *,
        enable_file_chooser_opened_event: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableParams(
            enableFileChooserOpenedEvent=enable_file_chooser_opened_event
        )

        result = await self._client.send_raw(
            method=PageCommand.ENABLE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def get_app_manifest(
        self,
        *,
        manifest_id: str | None = None,
        session_id: str | None = None,
    ) -> GetAppManifestResult:
        params = GetAppManifestParams(manifestId=manifest_id)

        result = await self._client.send_raw(
            method=PageCommand.GET_APP_MANIFEST,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetAppManifestResult.model_validate(result)

    async def get_installability_errors(
        self,
        session_id: str | None = None,
    ) -> GetInstallabilityErrorsResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_INSTALLABILITY_ERRORS,
            params=None,
            session_id=session_id,
        )
        return GetInstallabilityErrorsResult.model_validate(result)

    async def get_manifest_icons(
        self,
        session_id: str | None = None,
    ) -> GetManifestIconsResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_MANIFEST_ICONS,
            params=None,
            session_id=session_id,
        )
        return GetManifestIconsResult.model_validate(result)

    async def get_app_id(
        self,
        session_id: str | None = None,
    ) -> GetAppIdResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_APP_ID,
            params=None,
            session_id=session_id,
        )
        return GetAppIdResult.model_validate(result)

    async def get_ad_script_ancestry(
        self,
        *,
        frame_id: FrameId,
        session_id: str | None = None,
    ) -> GetAdScriptAncestryResult:
        params = GetAdScriptAncestryParams(frameId=frame_id)

        result = await self._client.send_raw(
            method=PageCommand.GET_AD_SCRIPT_ANCESTRY,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetAdScriptAncestryResult.model_validate(result)

    async def get_frame_tree(
        self,
        session_id: str | None = None,
    ) -> GetFrameTreeResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_FRAME_TREE,
            params=None,
            session_id=session_id,
        )
        return GetFrameTreeResult.model_validate(result)

    async def get_layout_metrics(
        self,
        session_id: str | None = None,
    ) -> GetLayoutMetricsResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_LAYOUT_METRICS,
            params=None,
            session_id=session_id,
        )
        return GetLayoutMetricsResult.model_validate(result)

    async def get_navigation_history(
        self,
        session_id: str | None = None,
    ) -> GetNavigationHistoryResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_NAVIGATION_HISTORY,
            params=None,
            session_id=session_id,
        )
        return GetNavigationHistoryResult.model_validate(result)

    async def reset_navigation_history(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.RESET_NAVIGATION_HISTORY,
            params=None,
            session_id=session_id,
        )
        return result

    async def get_resource_content(
        self,
        *,
        frame_id: FrameId,
        url: str,
        session_id: str | None = None,
    ) -> GetResourceContentResult:
        params = GetResourceContentParams(frameId=frame_id, url=url)

        result = await self._client.send_raw(
            method=PageCommand.GET_RESOURCE_CONTENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetResourceContentResult.model_validate(result)

    async def get_resource_tree(
        self,
        session_id: str | None = None,
    ) -> GetResourceTreeResult:
        result = await self._client.send_raw(
            method=PageCommand.GET_RESOURCE_TREE,
            params=None,
            session_id=session_id,
        )
        return GetResourceTreeResult.model_validate(result)

    async def handle_java_script_dialog(
        self,
        *,
        accept: bool,
        prompt_text: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = HandleJavaScriptDialogParams(accept=accept, promptText=prompt_text)

        result = await self._client.send_raw(
            method=PageCommand.HANDLE_JAVA_SCRIPT_DIALOG,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def navigate(
        self,
        *,
        url: str,
        referrer: str | None = None,
        transition_type: TransitionType | None = None,
        frame_id: FrameId | None = None,
        referrer_policy: ReferrerPolicy | None = None,
        session_id: str | None = None,
    ) -> NavigateResult:
        params = NavigateParams(
            url=url,
            referrer=referrer,
            transitionType=transition_type,
            frameId=frame_id,
            referrerPolicy=referrer_policy,
        )

        result = await self._client.send_raw(
            method=PageCommand.NAVIGATE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return NavigateResult.model_validate(result)

    async def navigate_to_history_entry(
        self,
        *,
        entry_id: int,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = NavigateToHistoryEntryParams(entryId=entry_id)

        result = await self._client.send_raw(
            method=PageCommand.NAVIGATE_TO_HISTORY_ENTRY,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def print_to_p_d_f(
        self,
        *,
        landscape: bool | None = None,
        display_header_footer: bool | None = None,
        print_background: bool | None = None,
        scale: float | None = None,
        paper_width: float | None = None,
        paper_height: float | None = None,
        margin_top: float | None = None,
        margin_bottom: float | None = None,
        margin_left: float | None = None,
        margin_right: float | None = None,
        page_ranges: str | None = None,
        header_template: str | None = None,
        footer_template: str | None = None,
        prefer_c_s_s_page_size: bool | None = None,
        transfer_mode: Literal["ReturnAsBase64", "ReturnAsStream"] | None = None,
        generate_tagged_p_d_f: bool | None = None,
        generate_document_outline: bool | None = None,
        session_id: str | None = None,
    ) -> PrintToPDFResult:
        params = PrintToPDFParams(
            landscape=landscape,
            displayHeaderFooter=display_header_footer,
            printBackground=print_background,
            scale=scale,
            paperWidth=paper_width,
            paperHeight=paper_height,
            marginTop=margin_top,
            marginBottom=margin_bottom,
            marginLeft=margin_left,
            marginRight=margin_right,
            pageRanges=page_ranges,
            headerTemplate=header_template,
            footerTemplate=footer_template,
            preferCSSPageSize=prefer_c_s_s_page_size,
            transferMode=transfer_mode,
            generateTaggedPDF=generate_tagged_p_d_f,
            generateDocumentOutline=generate_document_outline,
        )

        result = await self._client.send_raw(
            method=PageCommand.PRINT_TO_P_D_F,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return PrintToPDFResult.model_validate(result)

    async def reload(
        self,
        *,
        ignore_cache: bool | None = None,
        script_to_evaluate_on_load: str | None = None,
        loader_id: Network.LoaderId | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ReloadParams(
            ignoreCache=ignore_cache,
            scriptToEvaluateOnLoad=script_to_evaluate_on_load,
            loaderId=loader_id,
        )

        result = await self._client.send_raw(
            method=PageCommand.RELOAD,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def remove_script_to_evaluate_on_load(
        self,
        *,
        identifier: ScriptIdentifier,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = RemoveScriptToEvaluateOnLoadParams(identifier=identifier)

        result = await self._client.send_raw(
            method=PageCommand.REMOVE_SCRIPT_TO_EVALUATE_ON_LOAD,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def remove_script_to_evaluate_on_new_document(
        self,
        *,
        identifier: ScriptIdentifier,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = RemoveScriptToEvaluateOnNewDocumentParams(identifier=identifier)

        result = await self._client.send_raw(
            method=PageCommand.REMOVE_SCRIPT_TO_EVALUATE_ON_NEW_DOCUMENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def screencast_frame_ack(
        self,
        *,
        screencast_frame_ack_session_id: int,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ScreencastFrameAckParams(sessionId=screencast_frame_ack_session_id)

        result = await self._client.send_raw(
            method=PageCommand.SCREENCAST_FRAME_ACK,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def search_in_resource(
        self,
        *,
        frame_id: FrameId,
        url: str,
        query: str,
        case_sensitive: bool | None = None,
        is_regex: bool | None = None,
        session_id: str | None = None,
    ) -> SearchInResourceResult:
        params = SearchInResourceParams(
            frameId=frame_id,
            url=url,
            query=query,
            caseSensitive=case_sensitive,
            isRegex=is_regex,
        )

        result = await self._client.send_raw(
            method=PageCommand.SEARCH_IN_RESOURCE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return SearchInResourceResult.model_validate(result)

    async def set_ad_blocking_enabled(
        self,
        *,
        enabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetAdBlockingEnabledParams(enabled=enabled)

        result = await self._client.send_raw(
            method=PageCommand.SET_AD_BLOCKING_ENABLED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_bypass_c_s_p(
        self,
        *,
        enabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetBypassCSPParams(enabled=enabled)

        result = await self._client.send_raw(
            method=PageCommand.SET_BYPASS_C_S_P,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def get_permissions_policy_state(
        self,
        *,
        frame_id: FrameId,
        session_id: str | None = None,
    ) -> GetPermissionsPolicyStateResult:
        params = GetPermissionsPolicyStateParams(frameId=frame_id)

        result = await self._client.send_raw(
            method=PageCommand.GET_PERMISSIONS_POLICY_STATE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetPermissionsPolicyStateResult.model_validate(result)

    async def get_origin_trials(
        self,
        *,
        frame_id: FrameId,
        session_id: str | None = None,
    ) -> GetOriginTrialsResult:
        params = GetOriginTrialsParams(frameId=frame_id)

        result = await self._client.send_raw(
            method=PageCommand.GET_ORIGIN_TRIALS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetOriginTrialsResult.model_validate(result)

    async def set_device_metrics_override(
        self,
        *,
        width: int,
        height: int,
        device_scale_factor: float,
        mobile: bool,
        scale: float | None = None,
        screen_width: int | None = None,
        screen_height: int | None = None,
        position_x: int | None = None,
        position_y: int | None = None,
        dont_set_visible_size: bool | None = None,
        screen_orientation: Emulation.ScreenOrientation | None = None,
        viewport: Viewport | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDeviceMetricsOverrideParams(
            width=width,
            height=height,
            deviceScaleFactor=device_scale_factor,
            mobile=mobile,
            scale=scale,
            screenWidth=screen_width,
            screenHeight=screen_height,
            positionX=position_x,
            positionY=position_y,
            dontSetVisibleSize=dont_set_visible_size,
            screenOrientation=screen_orientation,
            viewport=viewport,
        )

        result = await self._client.send_raw(
            method=PageCommand.SET_DEVICE_METRICS_OVERRIDE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_device_orientation_override(
        self,
        *,
        alpha: float,
        beta: float,
        gamma: float,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDeviceOrientationOverrideParams(alpha=alpha, beta=beta, gamma=gamma)

        result = await self._client.send_raw(
            method=PageCommand.SET_DEVICE_ORIENTATION_OVERRIDE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_font_families(
        self,
        *,
        font_families: FontFamilies,
        for_scripts: list[ScriptFontFamilies] | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetFontFamiliesParams(
            fontFamilies=font_families, forScripts=for_scripts
        )

        result = await self._client.send_raw(
            method=PageCommand.SET_FONT_FAMILIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_font_sizes(
        self,
        *,
        font_sizes: FontSizes,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetFontSizesParams(fontSizes=font_sizes)

        result = await self._client.send_raw(
            method=PageCommand.SET_FONT_SIZES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_document_content(
        self,
        *,
        frame_id: FrameId,
        html: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDocumentContentParams(frameId=frame_id, html=html)

        result = await self._client.send_raw(
            method=PageCommand.SET_DOCUMENT_CONTENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_download_behavior(
        self,
        *,
        behavior: Literal["deny", "allow", "default"],
        download_path: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetDownloadBehaviorParams(
            behavior=behavior, downloadPath=download_path
        )

        result = await self._client.send_raw(
            method=PageCommand.SET_DOWNLOAD_BEHAVIOR,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_geolocation_override(
        self,
        *,
        latitude: float | None = None,
        longitude: float | None = None,
        accuracy: float | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetGeolocationOverrideParams(
            latitude=latitude, longitude=longitude, accuracy=accuracy
        )

        result = await self._client.send_raw(
            method=PageCommand.SET_GEOLOCATION_OVERRIDE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_lifecycle_events_enabled(
        self,
        *,
        enabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetLifecycleEventsEnabledParams(enabled=enabled)

        result = await self._client.send_raw(
            method=PageCommand.SET_LIFECYCLE_EVENTS_ENABLED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_touch_emulation_enabled(
        self,
        *,
        enabled: bool,
        configuration: Literal["mobile", "desktop"] | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetTouchEmulationEnabledParams(
            enabled=enabled, configuration=configuration
        )

        result = await self._client.send_raw(
            method=PageCommand.SET_TOUCH_EMULATION_ENABLED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def start_screencast(
        self,
        *,
        format: Literal["jpeg", "png"] | None = None,
        quality: int | None = None,
        max_width: int | None = None,
        max_height: int | None = None,
        every_nth_frame: int | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = StartScreencastParams(
            format=format,
            quality=quality,
            maxWidth=max_width,
            maxHeight=max_height,
            everyNthFrame=every_nth_frame,
        )

        result = await self._client.send_raw(
            method=PageCommand.START_SCREENCAST,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def stop_loading(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.STOP_LOADING,
            params=None,
            session_id=session_id,
        )
        return result

    async def crash(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CRASH,
            params=None,
            session_id=session_id,
        )
        return result

    async def close(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CLOSE,
            params=None,
            session_id=session_id,
        )
        return result

    async def set_web_lifecycle_state(
        self,
        *,
        state: Literal["frozen", "active"],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetWebLifecycleStateParams(state=state)

        result = await self._client.send_raw(
            method=PageCommand.SET_WEB_LIFECYCLE_STATE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def stop_screencast(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.STOP_SCREENCAST,
            params=None,
            session_id=session_id,
        )
        return result

    async def produce_compilation_cache(
        self,
        *,
        scripts: list[CompilationCacheParams],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ProduceCompilationCacheParams(scripts=scripts)

        result = await self._client.send_raw(
            method=PageCommand.PRODUCE_COMPILATION_CACHE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def add_compilation_cache(
        self,
        *,
        url: str,
        data: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = AddCompilationCacheParams(url=url, data=data)

        result = await self._client.send_raw(
            method=PageCommand.ADD_COMPILATION_CACHE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def clear_compilation_cache(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.CLEAR_COMPILATION_CACHE,
            params=None,
            session_id=session_id,
        )
        return result

    async def set_s_p_c_transaction_mode(
        self,
        *,
        mode: Literal[
            "none",
            "autoAccept",
            "autoChooseToAuthAnotherWay",
            "autoReject",
            "autoOptOut",
        ],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetSPCTransactionModeParams(mode=mode)

        result = await self._client.send_raw(
            method=PageCommand.SET_S_P_C_TRANSACTION_MODE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_r_p_h_registration_mode(
        self,
        *,
        mode: Literal["none", "autoAccept", "autoReject"],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetRPHRegistrationModeParams(mode=mode)

        result = await self._client.send_raw(
            method=PageCommand.SET_R_P_H_REGISTRATION_MODE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def generate_test_report(
        self,
        *,
        message: str,
        group: str | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = GenerateTestReportParams(message=message, group=group)

        result = await self._client.send_raw(
            method=PageCommand.GENERATE_TEST_REPORT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def wait_for_debugger(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=PageCommand.WAIT_FOR_DEBUGGER,
            params=None,
            session_id=session_id,
        )
        return result

    async def set_intercept_file_chooser_dialog(
        self,
        *,
        enabled: bool,
        cancel: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetInterceptFileChooserDialogParams(enabled=enabled, cancel=cancel)

        result = await self._client.send_raw(
            method=PageCommand.SET_INTERCEPT_FILE_CHOOSER_DIALOG,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_prerendering_allowed(
        self,
        *,
        is_allowed: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetPrerenderingAllowedParams(isAllowed=is_allowed)

        result = await self._client.send_raw(
            method=PageCommand.SET_PRERENDERING_ALLOWED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def get_annotated_page_content(
        self,
        *,
        include_actionable_information: bool | None = None,
        session_id: str | None = None,
    ) -> GetAnnotatedPageContentResult:
        params = GetAnnotatedPageContentParams(
            includeActionableInformation=include_actionable_information
        )

        result = await self._client.send_raw(
            method=PageCommand.GET_ANNOTATED_PAGE_CONTENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetAnnotatedPageContentResult.model_validate(result)
