# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import TYPE_CHECKING
from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *

if TYPE_CHECKING:
    from cdpify.domains import dom


class LayerTreeEvent(StrEnum):
    LAYER_PAINTED = "LayerTree.layerPainted"
    LAYER_TREE_DID_CHANGE = "LayerTree.layerTreeDidChange"


class LayerPaintedEvent(CDPModel):
    layer_id: LayerId
    clip: dom.Rect


class LayerTreeDidChangeEvent(CDPModel):
    layers: list[Layer] | None = None
