# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class SystemInfoCommand(StrEnum):
    GET_INFO = "SystemInfo.getInfo"
    GET_FEATURE_STATE = "SystemInfo.getFeatureState"
    GET_PROCESS_INFO = "SystemInfo.getProcessInfo"


class GetInfoResult(CDPModel):
    gpu: GPUInfo
    model_name: str
    model_version: str
    command_line: str


class GetFeatureStateParams(CDPModel):
    """
    Returns information about the feature state.
    """

    feature_state: str


class GetFeatureStateResult(CDPModel):
    feature_enabled: bool


class GetProcessInfoResult(CDPModel):
    process_info: list[ProcessInfo]
