# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class ServiceWorkerCommand(StrEnum):
    DELIVER_PUSH_MESSAGE = "ServiceWorker.deliverPushMessage"
    DISABLE = "ServiceWorker.disable"
    DISPATCH_SYNC_EVENT = "ServiceWorker.dispatchSyncEvent"
    DISPATCH_PERIODIC_SYNC_EVENT = "ServiceWorker.dispatchPeriodicSyncEvent"
    ENABLE = "ServiceWorker.enable"
    SET_FORCE_UPDATE_ON_PAGE_LOAD = "ServiceWorker.setForceUpdateOnPageLoad"
    SKIP_WAITING = "ServiceWorker.skipWaiting"
    START_WORKER = "ServiceWorker.startWorker"
    STOP_ALL_WORKERS = "ServiceWorker.stopAllWorkers"
    STOP_WORKER = "ServiceWorker.stopWorker"
    UNREGISTER = "ServiceWorker.unregister"
    UPDATE_REGISTRATION = "ServiceWorker.updateRegistration"


class DeliverPushMessageParams(CDPModel):
    origin: str
    registration_id: RegistrationID
    data: str


class DispatchSyncEventParams(CDPModel):
    origin: str
    registration_id: RegistrationID
    tag: str
    last_chance: bool


class DispatchPeriodicSyncEventParams(CDPModel):
    origin: str
    registration_id: RegistrationID
    tag: str


class SetForceUpdateOnPageLoadParams(CDPModel):
    force_update_on_page_load: bool


class SkipWaitingParams(CDPModel):
    scope_u_r_l: str


class StartWorkerParams(CDPModel):
    scope_u_r_l: str


class StopWorkerParams(CDPModel):
    version_id: str


class UnregisterParams(CDPModel):
    scope_u_r_l: str


class UpdateRegistrationParams(CDPModel):
    scope_u_r_l: str
