# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from cdpify.client import CDPClient

from .commands import (
    WebAuthnCommand,
    AddCredentialParams,
    AddVirtualAuthenticatorParams,
    AddVirtualAuthenticatorResult,
    ClearCredentialsParams,
    EnableParams,
    GetCredentialParams,
    GetCredentialResult,
    GetCredentialsParams,
    GetCredentialsResult,
    RemoveCredentialParams,
    RemoveVirtualAuthenticatorParams,
    SetAutomaticPresenceSimulationParams,
    SetCredentialPropertiesParams,
    SetResponseOverrideBitsParams,
    SetUserVerifiedParams,
)

from .types import (
    AuthenticatorId,
    Credential,
    VirtualAuthenticatorOptions,
)


class WebAuthnClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def enable(
        self,
        *,
        enable_u_i: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableParams(enableUI=enable_u_i)

        result = await self._client.send_raw(
            method=WebAuthnCommand.ENABLE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=WebAuthnCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def add_virtual_authenticator(
        self,
        *,
        options: VirtualAuthenticatorOptions,
        session_id: str | None = None,
    ) -> AddVirtualAuthenticatorResult:
        params = AddVirtualAuthenticatorParams(options=options)

        result = await self._client.send_raw(
            method=WebAuthnCommand.ADD_VIRTUAL_AUTHENTICATOR,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return AddVirtualAuthenticatorResult.model_validate(result)

    async def set_response_override_bits(
        self,
        *,
        authenticator_id: AuthenticatorId,
        is_bogus_signature: bool | None = None,
        is_bad_u_v: bool | None = None,
        is_bad_u_p: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetResponseOverrideBitsParams(
            authenticatorId=authenticator_id,
            isBogusSignature=is_bogus_signature,
            isBadUV=is_bad_u_v,
            isBadUP=is_bad_u_p,
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.SET_RESPONSE_OVERRIDE_BITS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def remove_virtual_authenticator(
        self,
        *,
        authenticator_id: AuthenticatorId,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = RemoveVirtualAuthenticatorParams(authenticatorId=authenticator_id)

        result = await self._client.send_raw(
            method=WebAuthnCommand.REMOVE_VIRTUAL_AUTHENTICATOR,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def add_credential(
        self,
        *,
        authenticator_id: AuthenticatorId,
        credential: Credential,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = AddCredentialParams(
            authenticatorId=authenticator_id, credential=credential
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.ADD_CREDENTIAL,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def get_credential(
        self,
        *,
        authenticator_id: AuthenticatorId,
        credential_id: str,
        session_id: str | None = None,
    ) -> GetCredentialResult:
        params = GetCredentialParams(
            authenticatorId=authenticator_id, credentialId=credential_id
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.GET_CREDENTIAL,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetCredentialResult.model_validate(result)

    async def get_credentials(
        self,
        *,
        authenticator_id: AuthenticatorId,
        session_id: str | None = None,
    ) -> GetCredentialsResult:
        params = GetCredentialsParams(authenticatorId=authenticator_id)

        result = await self._client.send_raw(
            method=WebAuthnCommand.GET_CREDENTIALS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetCredentialsResult.model_validate(result)

    async def remove_credential(
        self,
        *,
        authenticator_id: AuthenticatorId,
        credential_id: str,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = RemoveCredentialParams(
            authenticatorId=authenticator_id, credentialId=credential_id
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.REMOVE_CREDENTIAL,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def clear_credentials(
        self,
        *,
        authenticator_id: AuthenticatorId,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ClearCredentialsParams(authenticatorId=authenticator_id)

        result = await self._client.send_raw(
            method=WebAuthnCommand.CLEAR_CREDENTIALS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_user_verified(
        self,
        *,
        authenticator_id: AuthenticatorId,
        is_user_verified: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetUserVerifiedParams(
            authenticatorId=authenticator_id, isUserVerified=is_user_verified
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.SET_USER_VERIFIED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_automatic_presence_simulation(
        self,
        *,
        authenticator_id: AuthenticatorId,
        enabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetAutomaticPresenceSimulationParams(
            authenticatorId=authenticator_id, enabled=enabled
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.SET_AUTOMATIC_PRESENCE_SIMULATION,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_credential_properties(
        self,
        *,
        authenticator_id: AuthenticatorId,
        credential_id: str,
        backup_eligibility: bool | None = None,
        backup_state: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetCredentialPropertiesParams(
            authenticatorId=authenticator_id,
            credentialId=credential_id,
            backupEligibility=backup_eligibility,
            backupState=backup_state,
        )

        result = await self._client.send_raw(
            method=WebAuthnCommand.SET_CREDENTIAL_PROPERTIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
