# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class DOMStorageCommand(StrEnum):
    CLEAR = "DOMStorage.clear"
    DISABLE = "DOMStorage.disable"
    ENABLE = "DOMStorage.enable"
    GET_D_O_M_STORAGE_ITEMS = "DOMStorage.getDOMStorageItems"
    REMOVE_D_O_M_STORAGE_ITEM = "DOMStorage.removeDOMStorageItem"
    SET_D_O_M_STORAGE_ITEM = "DOMStorage.setDOMStorageItem"


class ClearParams(CDPModel):
    storage_id: StorageId


class GetDOMStorageItemsParams(CDPModel):
    storage_id: StorageId


class GetDOMStorageItemsResult(CDPModel):
    entries: list[Item]


class RemoveDOMStorageItemParams(CDPModel):
    storage_id: StorageId
    key: str


class SetDOMStorageItemParams(CDPModel):
    storage_id: StorageId
    key: str
    value: str
