# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class LogCommand(StrEnum):
    CLEAR = "Log.clear"
    DISABLE = "Log.disable"
    ENABLE = "Log.enable"
    START_VIOLATIONS_REPORT = "Log.startViolationsReport"
    STOP_VIOLATIONS_REPORT = "Log.stopViolationsReport"


class StartViolationsReportParams(CDPModel):
    """
    start violation reporting.
    """

    config: list[ViolationSetting]
