# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class ProfilerCommand(StrEnum):
    DISABLE = "Profiler.disable"
    ENABLE = "Profiler.enable"
    GET_BEST_EFFORT_COVERAGE = "Profiler.getBestEffortCoverage"
    SET_SAMPLING_INTERVAL = "Profiler.setSamplingInterval"
    START = "Profiler.start"
    START_PRECISE_COVERAGE = "Profiler.startPreciseCoverage"
    STOP = "Profiler.stop"
    STOP_PRECISE_COVERAGE = "Profiler.stopPreciseCoverage"
    TAKE_PRECISE_COVERAGE = "Profiler.takePreciseCoverage"


class GetBestEffortCoverageResult(CDPModel):
    result: list[ScriptCoverage]


class SetSamplingIntervalParams(CDPModel):
    """
    Changes CPU profiler sampling interval. Must be called before CPU profiles
    recording started.
    """

    interval: int


class StartPreciseCoverageParams(CDPModel):
    """
    Enable precise code coverage. Coverage data for JavaScript executed before enabling
    precise code coverage may be incomplete. Enabling prevents running optimized code
    and resets execution counters.
    """

    call_count: bool | None = None
    detailed: bool | None = None
    allow_triggered_updates: bool | None = None


class StartPreciseCoverageResult(CDPModel):
    timestamp: float


class StopResult(CDPModel):
    profile: Profile


class TakePreciseCoverageResult(CDPModel):
    result: list[ScriptCoverage]
    timestamp: float
