# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class SchemaCommand(StrEnum):
    GET_DOMAINS = "Schema.getDomains"


class GetDomainsResult(CDPModel):
    domains: list[Domain]
