# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import Literal, TYPE_CHECKING
from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *

from cdpify.domains import dom
from cdpify.domains import page
from cdpify.domains import runtime


class DOMCommand(StrEnum):
    COLLECT_CLASS_NAMES_FROM_SUBTREE = "DOM.collectClassNamesFromSubtree"
    COPY_TO = "DOM.copyTo"
    DESCRIBE_NODE = "DOM.describeNode"
    SCROLL_INTO_VIEW_IF_NEEDED = "DOM.scrollIntoViewIfNeeded"
    DISABLE = "DOM.disable"
    DISCARD_SEARCH_RESULTS = "DOM.discardSearchResults"
    ENABLE = "DOM.enable"
    FOCUS = "DOM.focus"
    GET_ATTRIBUTES = "DOM.getAttributes"
    GET_BOX_MODEL = "DOM.getBoxModel"
    GET_CONTENT_QUADS = "DOM.getContentQuads"
    GET_DOCUMENT = "DOM.getDocument"
    GET_FLATTENED_DOCUMENT = "DOM.getFlattenedDocument"
    GET_NODES_FOR_SUBTREE_BY_STYLE = "DOM.getNodesForSubtreeByStyle"
    GET_NODE_FOR_LOCATION = "DOM.getNodeForLocation"
    GET_OUTER_H_T_M_L = "DOM.getOuterHTML"
    GET_RELAYOUT_BOUNDARY = "DOM.getRelayoutBoundary"
    GET_SEARCH_RESULTS = "DOM.getSearchResults"
    HIDE_HIGHLIGHT = "DOM.hideHighlight"
    HIGHLIGHT_NODE = "DOM.highlightNode"
    HIGHLIGHT_RECT = "DOM.highlightRect"
    MARK_UNDOABLE_STATE = "DOM.markUndoableState"
    MOVE_TO = "DOM.moveTo"
    PERFORM_SEARCH = "DOM.performSearch"
    PUSH_NODE_BY_PATH_TO_FRONTEND = "DOM.pushNodeByPathToFrontend"
    PUSH_NODES_BY_BACKEND_IDS_TO_FRONTEND = "DOM.pushNodesByBackendIdsToFrontend"
    QUERY_SELECTOR = "DOM.querySelector"
    QUERY_SELECTOR_ALL = "DOM.querySelectorAll"
    GET_TOP_LAYER_ELEMENTS = "DOM.getTopLayerElements"
    GET_ELEMENT_BY_RELATION = "DOM.getElementByRelation"
    REDO = "DOM.redo"
    REMOVE_ATTRIBUTE = "DOM.removeAttribute"
    REMOVE_NODE = "DOM.removeNode"
    REQUEST_CHILD_NODES = "DOM.requestChildNodes"
    REQUEST_NODE = "DOM.requestNode"
    RESOLVE_NODE = "DOM.resolveNode"
    SET_ATTRIBUTE_VALUE = "DOM.setAttributeValue"
    SET_ATTRIBUTES_AS_TEXT = "DOM.setAttributesAsText"
    SET_FILE_INPUT_FILES = "DOM.setFileInputFiles"
    SET_NODE_STACK_TRACES_ENABLED = "DOM.setNodeStackTracesEnabled"
    GET_NODE_STACK_TRACES = "DOM.getNodeStackTraces"
    GET_FILE_INFO = "DOM.getFileInfo"
    GET_DETACHED_DOM_NODES = "DOM.getDetachedDomNodes"
    SET_INSPECTED_NODE = "DOM.setInspectedNode"
    SET_NODE_NAME = "DOM.setNodeName"
    SET_NODE_VALUE = "DOM.setNodeValue"
    SET_OUTER_H_T_M_L = "DOM.setOuterHTML"
    UNDO = "DOM.undo"
    GET_FRAME_OWNER = "DOM.getFrameOwner"
    GET_CONTAINER_FOR_NODE = "DOM.getContainerForNode"
    GET_QUERYING_DESCENDANTS_FOR_CONTAINER = "DOM.getQueryingDescendantsForContainer"
    GET_ANCHOR_ELEMENT = "DOM.getAnchorElement"
    FORCE_SHOW_POPOVER = "DOM.forceShowPopover"


class CollectClassNamesFromSubtreeParams(CDPModel):
    """
    Collects class names for the node with given id and all of it's child nodes.
    """

    node_id: NodeId


class CollectClassNamesFromSubtreeResult(CDPModel):
    class_names: list[str]


class CopyToParams(CDPModel):
    """
    Creates a deep copy of the specified node and places it into the target container
    before the given anchor.
    """

    node_id: NodeId
    target_node_id: NodeId
    insert_before_node_id: NodeId | None = None


class CopyToResult(CDPModel):
    node_id: NodeId


class DescribeNodeParams(CDPModel):
    """
    Describes node given its id, does not require domain to be enabled. Does not start
    tracking any objects, can be used for automation.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None
    depth: int | None = None
    pierce: bool | None = None


class DescribeNodeResult(CDPModel):
    node: Node


class ScrollIntoViewIfNeededParams(CDPModel):
    """
    Scrolls the specified rect of the given node into view if not already visible.
    Note: exactly one between nodeId, backendNodeId and objectId should be passed to
    identify the node.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None
    rect: Rect | None = None


class DiscardSearchResultsParams(CDPModel):
    """
    Discards search results from the session with the given id. `getSearchResults`
    should no longer be called for that search.
    """

    search_id: str


class EnableParams(CDPModel):
    """
    Enables DOM agent for the given page.
    """

    include_whitespace: Literal["none", "all"] | None = None


class FocusParams(CDPModel):
    """
    Focuses the given element.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None


class GetAttributesParams(CDPModel):
    """
    Returns attributes for the specified node.
    """

    node_id: NodeId


class GetAttributesResult(CDPModel):
    attributes: list[str]


class GetBoxModelParams(CDPModel):
    """
    Returns boxes for the given node.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None


class GetBoxModelResult(CDPModel):
    model: BoxModel


class GetContentQuadsParams(CDPModel):
    """
    Returns quads that describe node position on the page. This method might return
    multiple quads for inline nodes.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None


class GetContentQuadsResult(CDPModel):
    quads: list[Quad]


class GetDocumentParams(CDPModel):
    """
    Returns the root DOM node (and optionally the subtree) to the caller. Implicitly
    enables the DOM domain events for the current target.
    """

    depth: int | None = None
    pierce: bool | None = None


class GetDocumentResult(CDPModel):
    root: Node


class GetFlattenedDocumentParams(CDPModel):
    """
    Returns the root DOM node (and optionally the subtree) to the caller. Deprecated,
    as it is not designed to work well with the rest of the DOM agent. Use
    DOMSnapshot.captureSnapshot instead.
    """

    depth: int | None = None
    pierce: bool | None = None


class GetFlattenedDocumentResult(CDPModel):
    nodes: list[Node]


class GetNodesForSubtreeByStyleParams(CDPModel):
    """
    Finds nodes with a given computed style in a subtree.
    """

    node_id: NodeId
    computed_styles: list[CSSComputedStyleProperty]
    pierce: bool | None = None


class GetNodesForSubtreeByStyleResult(CDPModel):
    node_ids: list[NodeId]


class GetNodeForLocationParams(CDPModel):
    """
    Returns node id at given location. Depending on whether DOM domain is enabled,
    nodeId is either returned or not.
    """

    x: int
    y: int
    include_user_agent_shadow_d_o_m: bool | None = None
    ignore_pointer_events_none: bool | None = None


class GetNodeForLocationResult(CDPModel):
    backend_node_id: BackendNodeId
    frame_id: page.FrameId
    node_id: NodeId | None = None


class GetOuterHTMLParams(CDPModel):
    """
    Returns node's HTML markup.
    """

    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None
    include_shadow_d_o_m: bool | None = None


class GetOuterHTMLResult(CDPModel):
    outer_h_t_m_l: str


class GetRelayoutBoundaryParams(CDPModel):
    """
    Returns the id of the nearest ancestor that is a relayout boundary.
    """

    node_id: NodeId


class GetRelayoutBoundaryResult(CDPModel):
    node_id: NodeId


class GetSearchResultsParams(CDPModel):
    """
    Returns search results from given `fromIndex` to given `toIndex` from the search
    with the given identifier.
    """

    search_id: str
    from_index: int
    to_index: int


class GetSearchResultsResult(CDPModel):
    node_ids: list[NodeId]


class MoveToParams(CDPModel):
    """
    Moves node into the new container, places it before the given anchor.
    """

    node_id: NodeId
    target_node_id: NodeId
    insert_before_node_id: NodeId | None = None


class MoveToResult(CDPModel):
    node_id: NodeId


class PerformSearchParams(CDPModel):
    """
    Searches for a given string in the DOM tree. Use `getSearchResults` to access
    search results or `cancelSearch` to end this search session.
    """

    query: str
    include_user_agent_shadow_d_o_m: bool | None = None


class PerformSearchResult(CDPModel):
    search_id: str
    result_count: int


class PushNodeByPathToFrontendParams(CDPModel):
    """
    Requests that the node is sent to the caller given its path. // FIXME, use XPath
    """

    path: str


class PushNodeByPathToFrontendResult(CDPModel):
    node_id: NodeId


class PushNodesByBackendIdsToFrontendParams(CDPModel):
    """
    Requests that a batch of nodes is sent to the caller given their backend node ids.
    """

    backend_node_ids: list[BackendNodeId]


class PushNodesByBackendIdsToFrontendResult(CDPModel):
    node_ids: list[NodeId]


class QuerySelectorParams(CDPModel):
    """
    Executes `querySelector` on a given node.
    """

    node_id: NodeId
    selector: str


class QuerySelectorResult(CDPModel):
    node_id: NodeId


class QuerySelectorAllParams(CDPModel):
    """
    Executes `querySelectorAll` on a given node.
    """

    node_id: NodeId
    selector: str


class QuerySelectorAllResult(CDPModel):
    node_ids: list[NodeId]


class GetTopLayerElementsResult(CDPModel):
    node_ids: list[NodeId]


class GetElementByRelationParams(CDPModel):
    """
    Returns the NodeId of the matched element according to certain relations.
    """

    node_id: NodeId
    relation: Literal["PopoverTarget", "InterestTarget", "CommandFor"]


class GetElementByRelationResult(CDPModel):
    node_id: NodeId


class RemoveAttributeParams(CDPModel):
    """
    Removes attribute with given name from an element with given id.
    """

    node_id: NodeId
    name: str


class RemoveNodeParams(CDPModel):
    """
    Removes node with given id.
    """

    node_id: NodeId


class RequestChildNodesParams(CDPModel):
    """
    Requests that children of the node with given id are returned to the caller in form
    of `setChildNodes` events where not only immediate children are retrieved, but all
    children down to the specified depth.
    """

    node_id: NodeId
    depth: int | None = None
    pierce: bool | None = None


class RequestNodeParams(CDPModel):
    """
    Requests that the node is sent to the caller given the JavaScript node object
    reference. All nodes that form the path from the node to the root are also sent to
    the client as a series of `setChildNodes` notifications.
    """

    object_id: runtime.RemoteObjectId


class RequestNodeResult(CDPModel):
    node_id: NodeId


class ResolveNodeParams(CDPModel):
    """
    Resolves the JavaScript node object for a given NodeId or BackendNodeId.
    """

    node_id: NodeId | None = None
    backend_node_id: dom.BackendNodeId | None = None
    object_group: str | None = None
    execution_context_id: runtime.ExecutionContextId | None = None


class ResolveNodeResult(CDPModel):
    object: runtime.RemoteObject


class SetAttributeValueParams(CDPModel):
    """
    Sets attribute for an element with given id.
    """

    node_id: NodeId
    name: str
    value: str


class SetAttributesAsTextParams(CDPModel):
    """
    Sets attributes on element with given id. This method is useful when user edits
    some existing attribute value and types in several attribute name/value pairs.
    """

    node_id: NodeId
    text: str
    name: str | None = None


class SetFileInputFilesParams(CDPModel):
    """
    Sets files for the given file input element.
    """

    files: list[str]
    node_id: NodeId | None = None
    backend_node_id: BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None


class SetNodeStackTracesEnabledParams(CDPModel):
    """
    Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`.
    Default is disabled.
    """

    enable: bool


class GetNodeStackTracesParams(CDPModel):
    """
    Gets stack traces associated with a Node. As of now, only provides stack trace for
    Node creation.
    """

    node_id: NodeId


class GetNodeStackTracesResult(CDPModel):
    creation: runtime.StackTrace | None = None


class GetFileInfoParams(CDPModel):
    """
    Returns file information for the given File wrapper.
    """

    object_id: runtime.RemoteObjectId


class GetFileInfoResult(CDPModel):
    path: str


class GetDetachedDomNodesResult(CDPModel):
    detached_nodes: list[DetachedElementInfo]


class SetInspectedNodeParams(CDPModel):
    """
    Enables console to refer to the node with given id via $x (see Command Line API for
    more details $x functions).
    """

    node_id: NodeId


class SetNodeNameParams(CDPModel):
    """
    Sets node name for a node with given id.
    """

    node_id: NodeId
    name: str


class SetNodeNameResult(CDPModel):
    node_id: NodeId


class SetNodeValueParams(CDPModel):
    """
    Sets node value for a node with given id.
    """

    node_id: NodeId
    value: str


class SetOuterHTMLParams(CDPModel):
    """
    Sets node HTML markup, returns new node id.
    """

    node_id: NodeId
    outer_h_t_m_l: str


class GetFrameOwnerParams(CDPModel):
    """
    Returns iframe node that owns iframe with the given domain.
    """

    frame_id: page.FrameId


class GetFrameOwnerResult(CDPModel):
    backend_node_id: BackendNodeId
    node_id: NodeId | None = None


class GetContainerForNodeParams(CDPModel):
    """
    Returns the query container of the given node based on container query conditions:
    containerName, physical and logical axes, and whether it queries scroll-state or
    anchored elements. If no axes are provided and queriesScrollState is false, the
    style container is returned, which is the direct parent or the closest element with
    a matching container-name.
    """

    node_id: NodeId
    container_name: str | None = None
    physical_axes: PhysicalAxes | None = None
    logical_axes: LogicalAxes | None = None
    queries_scroll_state: bool | None = None
    queries_anchored: bool | None = None


class GetContainerForNodeResult(CDPModel):
    node_id: NodeId | None = None


class GetQueryingDescendantsForContainerParams(CDPModel):
    """
    Returns the descendants of a container query container that have container queries
    against this container.
    """

    node_id: NodeId


class GetQueryingDescendantsForContainerResult(CDPModel):
    node_ids: list[NodeId]


class GetAnchorElementParams(CDPModel):
    """
    Returns the target anchor element of the given anchor query according to
    https://www.w3.org/TR/css-anchor-position-1/#target.
    """

    node_id: NodeId
    anchor_specifier: str | None = None


class GetAnchorElementResult(CDPModel):
    node_id: NodeId


class ForceShowPopoverParams(CDPModel):
    """
    When enabling, this API force-opens the popover identified by nodeId and keeps it
    open until disabled.
    """

    node_id: NodeId
    enable: bool


class ForceShowPopoverResult(CDPModel):
    node_ids: list[NodeId]
