# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class DeviceOrientationCommand(StrEnum):
    CLEAR_DEVICE_ORIENTATION_OVERRIDE = (
        "DeviceOrientation.clearDeviceOrientationOverride"
    )
    SET_DEVICE_ORIENTATION_OVERRIDE = "DeviceOrientation.setDeviceOrientationOverride"


class SetDeviceOrientationOverrideParams(CDPModel):
    """
    Overrides the Device Orientation.
    """

    alpha: float
    beta: float
    gamma: float
