# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import Any, TYPE_CHECKING
from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *

from cdpify.domains import dom
from cdpify.domains import page
from cdpify.domains import runtime


class OverlayCommand(StrEnum):
    DISABLE = "Overlay.disable"
    ENABLE = "Overlay.enable"
    GET_HIGHLIGHT_OBJECT_FOR_TEST = "Overlay.getHighlightObjectForTest"
    GET_GRID_HIGHLIGHT_OBJECTS_FOR_TEST = "Overlay.getGridHighlightObjectsForTest"
    GET_SOURCE_ORDER_HIGHLIGHT_OBJECT_FOR_TEST = (
        "Overlay.getSourceOrderHighlightObjectForTest"
    )
    HIDE_HIGHLIGHT = "Overlay.hideHighlight"
    HIGHLIGHT_FRAME = "Overlay.highlightFrame"
    HIGHLIGHT_NODE = "Overlay.highlightNode"
    HIGHLIGHT_QUAD = "Overlay.highlightQuad"
    HIGHLIGHT_RECT = "Overlay.highlightRect"
    HIGHLIGHT_SOURCE_ORDER = "Overlay.highlightSourceOrder"
    SET_INSPECT_MODE = "Overlay.setInspectMode"
    SET_SHOW_AD_HIGHLIGHTS = "Overlay.setShowAdHighlights"
    SET_PAUSED_IN_DEBUGGER_MESSAGE = "Overlay.setPausedInDebuggerMessage"
    SET_SHOW_DEBUG_BORDERS = "Overlay.setShowDebugBorders"
    SET_SHOW_F_P_S_COUNTER = "Overlay.setShowFPSCounter"
    SET_SHOW_GRID_OVERLAYS = "Overlay.setShowGridOverlays"
    SET_SHOW_FLEX_OVERLAYS = "Overlay.setShowFlexOverlays"
    SET_SHOW_SCROLL_SNAP_OVERLAYS = "Overlay.setShowScrollSnapOverlays"
    SET_SHOW_CONTAINER_QUERY_OVERLAYS = "Overlay.setShowContainerQueryOverlays"
    SET_SHOW_PAINT_RECTS = "Overlay.setShowPaintRects"
    SET_SHOW_LAYOUT_SHIFT_REGIONS = "Overlay.setShowLayoutShiftRegions"
    SET_SHOW_SCROLL_BOTTLENECK_RECTS = "Overlay.setShowScrollBottleneckRects"
    SET_SHOW_HIT_TEST_BORDERS = "Overlay.setShowHitTestBorders"
    SET_SHOW_WEB_VITALS = "Overlay.setShowWebVitals"
    SET_SHOW_VIEWPORT_SIZE_ON_RESIZE = "Overlay.setShowViewportSizeOnResize"
    SET_SHOW_HINGE = "Overlay.setShowHinge"
    SET_SHOW_ISOLATED_ELEMENTS = "Overlay.setShowIsolatedElements"
    SET_SHOW_WINDOW_CONTROLS_OVERLAY = "Overlay.setShowWindowControlsOverlay"


class GetHighlightObjectForTestParams(CDPModel):
    """
    For testing.
    """

    node_id: dom.NodeId
    include_distance: bool | None = None
    include_style: bool | None = None
    color_format: ColorFormat | None = None
    show_accessibility_info: bool | None = None


class GetHighlightObjectForTestResult(CDPModel):
    highlight: dict[str, Any]


class GetGridHighlightObjectsForTestParams(CDPModel):
    """
    For Persistent Grid testing.
    """

    node_ids: list[dom.NodeId]


class GetGridHighlightObjectsForTestResult(CDPModel):
    highlights: dict[str, Any]


class GetSourceOrderHighlightObjectForTestParams(CDPModel):
    """
    For Source Order Viewer testing.
    """

    node_id: dom.NodeId


class GetSourceOrderHighlightObjectForTestResult(CDPModel):
    highlight: dict[str, Any]


class HighlightFrameParams(CDPModel):
    """
    Highlights owner element of the frame with given id. Deprecated: Doesn't work
    reliably and cannot be fixed due to process separation (the owner node might be in a
    different process). Determine the owner node in the client and use highlightNode.
    """

    frame_id: page.FrameId
    content_color: dom.RGBA | None = None
    content_outline_color: dom.RGBA | None = None


class HighlightNodeParams(CDPModel):
    """
    Highlights DOM node with given id or with the given JavaScript object wrapper.
    Either nodeId or objectId must be specified.
    """

    highlight_config: HighlightConfig
    node_id: dom.NodeId | None = None
    backend_node_id: dom.BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None
    selector: str | None = None


class HighlightQuadParams(CDPModel):
    """
    Highlights given quad. Coordinates are absolute with respect to the main frame
    viewport.
    """

    quad: dom.Quad
    color: dom.RGBA | None = None
    outline_color: dom.RGBA | None = None


class HighlightRectParams(CDPModel):
    """
    Highlights given rectangle. Coordinates are absolute with respect to the main frame
    viewport. Issue: the method does not handle device pixel ratio (DPR) correctly. The
    coordinates currently have to be adjusted by the client if DPR is not 1 (see
    crbug.com/437807128).
    """

    x: int
    y: int
    width: int
    height: int
    color: dom.RGBA | None = None
    outline_color: dom.RGBA | None = None


class HighlightSourceOrderParams(CDPModel):
    """
    Highlights the source order of the children of the DOM node with given id or with
    the given JavaScript object wrapper. Either nodeId or objectId must be specified.
    """

    source_order_config: SourceOrderConfig
    node_id: dom.NodeId | None = None
    backend_node_id: dom.BackendNodeId | None = None
    object_id: runtime.RemoteObjectId | None = None


class SetInspectModeParams(CDPModel):
    """
    Enters the 'inspect' mode. In this mode, elements that user is hovering over are
    highlighted. Backend then generates 'inspectNodeRequested' event upon element
    selection.
    """

    mode: InspectMode
    highlight_config: HighlightConfig | None = None


class SetShowAdHighlightsParams(CDPModel):
    """
    Highlights owner element of all frames detected to be ads.
    """

    show: bool


class SetPausedInDebuggerMessageParams(CDPModel):
    message: str | None = None


class SetShowDebugBordersParams(CDPModel):
    """
    Requests that backend shows debug borders on layers
    """

    show: bool


class SetShowFPSCounterParams(CDPModel):
    """
    Requests that backend shows the FPS counter
    """

    show: bool


class SetShowGridOverlaysParams(CDPModel):
    """
    Highlight multiple elements with the CSS Grid overlay.
    """

    grid_node_highlight_configs: list[GridNodeHighlightConfig]


class SetShowFlexOverlaysParams(CDPModel):
    flex_node_highlight_configs: list[FlexNodeHighlightConfig]


class SetShowScrollSnapOverlaysParams(CDPModel):
    scroll_snap_highlight_configs: list[ScrollSnapHighlightConfig]


class SetShowContainerQueryOverlaysParams(CDPModel):
    container_query_highlight_configs: list[ContainerQueryHighlightConfig]


class SetShowPaintRectsParams(CDPModel):
    """
    Requests that backend shows paint rectangles
    """

    result: bool


class SetShowLayoutShiftRegionsParams(CDPModel):
    """
    Requests that backend shows layout shift regions
    """

    result: bool


class SetShowScrollBottleneckRectsParams(CDPModel):
    """
    Requests that backend shows scroll bottleneck rects
    """

    show: bool


class SetShowHitTestBordersParams(CDPModel):
    """
    Deprecated, no longer has any effect.
    """

    show: bool


class SetShowWebVitalsParams(CDPModel):
    """
    Deprecated, no longer has any effect.
    """

    show: bool


class SetShowViewportSizeOnResizeParams(CDPModel):
    """
    Paints viewport size upon main frame resize.
    """

    show: bool


class SetShowHingeParams(CDPModel):
    """
    Add a dual screen device hinge
    """

    hinge_config: HingeConfig | None = None


class SetShowIsolatedElementsParams(CDPModel):
    """
    Show elements in isolation mode with overlays.
    """

    isolated_element_highlight_configs: list[IsolatedElementHighlightConfig]


class SetShowWindowControlsOverlayParams(CDPModel):
    """
    Show Window Controls Overlay for PWA
    """

    window_controls_overlay_config: WindowControlsOverlayConfig | None = None
