# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class WebAudioCommand(StrEnum):
    ENABLE = "WebAudio.enable"
    DISABLE = "WebAudio.disable"
    GET_REALTIME_DATA = "WebAudio.getRealtimeData"


class GetRealtimeDataParams(CDPModel):
    """
    Fetch the realtime data from the registered contexts.
    """

    context_id: GraphObjectId


class GetRealtimeDataResult(CDPModel):
    realtime_data: ContextRealtimeData
