# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from cdpify.client import CDPClient

from .commands import (
    NetworkCommand,
    CanClearBrowserCacheResult,
    CanClearBrowserCookiesResult,
    CanEmulateNetworkConditionsResult,
    ConfigureDurableMessagesParams,
    ContinueInterceptedRequestParams,
    DeleteCookiesParams,
    EmulateNetworkConditionsByRuleParams,
    EmulateNetworkConditionsByRuleResult,
    EmulateNetworkConditionsParams,
    EnableDeviceBoundSessionsParams,
    EnableParams,
    EnableReportingApiParams,
    FetchSchemefulSiteParams,
    FetchSchemefulSiteResult,
    GetAllCookiesResult,
    GetCertificateParams,
    GetCertificateResult,
    GetCookiesParams,
    GetCookiesResult,
    GetRequestPostDataParams,
    GetRequestPostDataResult,
    GetResponseBodyForInterceptionParams,
    GetResponseBodyForInterceptionResult,
    GetResponseBodyParams,
    GetResponseBodyResult,
    GetSecurityIsolationStatusParams,
    GetSecurityIsolationStatusResult,
    LoadNetworkResourceParams,
    LoadNetworkResourceResult,
    OverrideNetworkStateParams,
    ReplayXHRParams,
    SearchInResponseBodyParams,
    SearchInResponseBodyResult,
    SetAcceptedEncodingsParams,
    SetAttachDebugStackParams,
    SetBlockedURLsParams,
    SetBypassServiceWorkerParams,
    SetCacheDisabledParams,
    SetCookieControlsParams,
    SetCookieParams,
    SetCookieResult,
    SetCookiesParams,
    SetExtraHTTPHeadersParams,
    SetRequestInterceptionParams,
    SetUserAgentOverrideParams,
    StreamResourceContentParams,
    StreamResourceContentResult,
    TakeResponseBodyForInterceptionAsStreamParams,
    TakeResponseBodyForInterceptionAsStreamResult,
)

from .types import (
    AuthChallengeResponse,
    BlockPattern,
    ConnectionType,
    ContentEncoding,
    CookieParam,
    CookiePartitionKey,
    CookiePriority,
    CookieSameSite,
    CookieSourceScheme,
    ErrorReason,
    Headers,
    InterceptionId,
    LoadNetworkResourceOptions,
    NetworkConditions,
    RequestId,
    RequestPattern,
    TimeSinceEpoch,
)


class NetworkClient:
    def __init__(self, client: CDPClient) -> None:
        self._client = client

    async def set_accepted_encodings(
        self,
        *,
        encodings: list[ContentEncoding],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetAcceptedEncodingsParams(encodings=encodings)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_ACCEPTED_ENCODINGS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def clear_accepted_encodings_override(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=NetworkCommand.CLEAR_ACCEPTED_ENCODINGS_OVERRIDE,
            params=None,
            session_id=session_id,
        )
        return result

    async def can_clear_browser_cache(
        self,
        session_id: str | None = None,
    ) -> CanClearBrowserCacheResult:
        result = await self._client.send_raw(
            method=NetworkCommand.CAN_CLEAR_BROWSER_CACHE,
            params=None,
            session_id=session_id,
        )
        return CanClearBrowserCacheResult.model_validate(result)

    async def can_clear_browser_cookies(
        self,
        session_id: str | None = None,
    ) -> CanClearBrowserCookiesResult:
        result = await self._client.send_raw(
            method=NetworkCommand.CAN_CLEAR_BROWSER_COOKIES,
            params=None,
            session_id=session_id,
        )
        return CanClearBrowserCookiesResult.model_validate(result)

    async def can_emulate_network_conditions(
        self,
        session_id: str | None = None,
    ) -> CanEmulateNetworkConditionsResult:
        result = await self._client.send_raw(
            method=NetworkCommand.CAN_EMULATE_NETWORK_CONDITIONS,
            params=None,
            session_id=session_id,
        )
        return CanEmulateNetworkConditionsResult.model_validate(result)

    async def clear_browser_cache(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=NetworkCommand.CLEAR_BROWSER_CACHE,
            params=None,
            session_id=session_id,
        )
        return result

    async def clear_browser_cookies(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=NetworkCommand.CLEAR_BROWSER_COOKIES,
            params=None,
            session_id=session_id,
        )
        return result

    async def continue_intercepted_request(
        self,
        *,
        interception_id: InterceptionId,
        error_reason: ErrorReason | None = None,
        raw_response: str | None = None,
        url: str | None = None,
        method: str | None = None,
        post_data: str | None = None,
        headers: Headers | None = None,
        auth_challenge_response: AuthChallengeResponse | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ContinueInterceptedRequestParams(
            interceptionId=interception_id,
            errorReason=error_reason,
            rawResponse=raw_response,
            url=url,
            method=method,
            postData=post_data,
            headers=headers,
            authChallengeResponse=auth_challenge_response,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.CONTINUE_INTERCEPTED_REQUEST,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def delete_cookies(
        self,
        *,
        name: str,
        url: str | None = None,
        domain: str | None = None,
        path: str | None = None,
        partition_key: CookiePartitionKey | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = DeleteCookiesParams(
            name=name, url=url, domain=domain, path=path, partitionKey=partition_key
        )

        result = await self._client.send_raw(
            method=NetworkCommand.DELETE_COOKIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def disable(
        self,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        result = await self._client.send_raw(
            method=NetworkCommand.DISABLE,
            params=None,
            session_id=session_id,
        )
        return result

    async def emulate_network_conditions(
        self,
        *,
        offline: bool,
        latency: float,
        download_throughput: float,
        upload_throughput: float,
        connection_type: ConnectionType | None = None,
        packet_loss: float | None = None,
        packet_queue_length: int | None = None,
        packet_reordering: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EmulateNetworkConditionsParams(
            offline=offline,
            latency=latency,
            downloadThroughput=download_throughput,
            uploadThroughput=upload_throughput,
            connectionType=connection_type,
            packetLoss=packet_loss,
            packetQueueLength=packet_queue_length,
            packetReordering=packet_reordering,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.EMULATE_NETWORK_CONDITIONS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def emulate_network_conditions_by_rule(
        self,
        *,
        offline: bool,
        matched_network_conditions: list[NetworkConditions],
        session_id: str | None = None,
    ) -> EmulateNetworkConditionsByRuleResult:
        params = EmulateNetworkConditionsByRuleParams(
            offline=offline, matchedNetworkConditions=matched_network_conditions
        )

        result = await self._client.send_raw(
            method=NetworkCommand.EMULATE_NETWORK_CONDITIONS_BY_RULE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return EmulateNetworkConditionsByRuleResult.model_validate(result)

    async def override_network_state(
        self,
        *,
        offline: bool,
        latency: float,
        download_throughput: float,
        upload_throughput: float,
        connection_type: ConnectionType | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = OverrideNetworkStateParams(
            offline=offline,
            latency=latency,
            downloadThroughput=download_throughput,
            uploadThroughput=upload_throughput,
            connectionType=connection_type,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.OVERRIDE_NETWORK_STATE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def enable(
        self,
        *,
        max_total_buffer_size: int | None = None,
        max_resource_buffer_size: int | None = None,
        max_post_data_size: int | None = None,
        report_direct_socket_traffic: bool | None = None,
        enable_durable_messages: bool | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableParams(
            maxTotalBufferSize=max_total_buffer_size,
            maxResourceBufferSize=max_resource_buffer_size,
            maxPostDataSize=max_post_data_size,
            reportDirectSocketTraffic=report_direct_socket_traffic,
            enableDurableMessages=enable_durable_messages,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.ENABLE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def configure_durable_messages(
        self,
        *,
        max_total_buffer_size: int | None = None,
        max_resource_buffer_size: int | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ConfigureDurableMessagesParams(
            maxTotalBufferSize=max_total_buffer_size,
            maxResourceBufferSize=max_resource_buffer_size,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.CONFIGURE_DURABLE_MESSAGES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def get_all_cookies(
        self,
        session_id: str | None = None,
    ) -> GetAllCookiesResult:
        result = await self._client.send_raw(
            method=NetworkCommand.GET_ALL_COOKIES,
            params=None,
            session_id=session_id,
        )
        return GetAllCookiesResult.model_validate(result)

    async def get_certificate(
        self,
        *,
        origin: str,
        session_id: str | None = None,
    ) -> GetCertificateResult:
        params = GetCertificateParams(origin=origin)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_CERTIFICATE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetCertificateResult.model_validate(result)

    async def get_cookies(
        self,
        *,
        urls: list[str] | None = None,
        session_id: str | None = None,
    ) -> GetCookiesResult:
        params = GetCookiesParams(urls=urls)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_COOKIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetCookiesResult.model_validate(result)

    async def get_response_body(
        self,
        *,
        request_id: RequestId,
        session_id: str | None = None,
    ) -> GetResponseBodyResult:
        params = GetResponseBodyParams(requestId=request_id)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_RESPONSE_BODY,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetResponseBodyResult.model_validate(result)

    async def get_request_post_data(
        self,
        *,
        request_id: RequestId,
        session_id: str | None = None,
    ) -> GetRequestPostDataResult:
        params = GetRequestPostDataParams(requestId=request_id)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_REQUEST_POST_DATA,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetRequestPostDataResult.model_validate(result)

    async def get_response_body_for_interception(
        self,
        *,
        interception_id: InterceptionId,
        session_id: str | None = None,
    ) -> GetResponseBodyForInterceptionResult:
        params = GetResponseBodyForInterceptionParams(interceptionId=interception_id)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_RESPONSE_BODY_FOR_INTERCEPTION,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetResponseBodyForInterceptionResult.model_validate(result)

    async def take_response_body_for_interception_as_stream(
        self,
        *,
        interception_id: InterceptionId,
        session_id: str | None = None,
    ) -> TakeResponseBodyForInterceptionAsStreamResult:
        params = TakeResponseBodyForInterceptionAsStreamParams(
            interceptionId=interception_id
        )

        result = await self._client.send_raw(
            method=NetworkCommand.TAKE_RESPONSE_BODY_FOR_INTERCEPTION_AS_STREAM,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return TakeResponseBodyForInterceptionAsStreamResult.model_validate(result)

    async def replay_x_h_r(
        self,
        *,
        request_id: RequestId,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = ReplayXHRParams(requestId=request_id)

        result = await self._client.send_raw(
            method=NetworkCommand.REPLAY_X_H_R,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def search_in_response_body(
        self,
        *,
        request_id: RequestId,
        query: str,
        case_sensitive: bool | None = None,
        is_regex: bool | None = None,
        session_id: str | None = None,
    ) -> SearchInResponseBodyResult:
        params = SearchInResponseBodyParams(
            requestId=request_id,
            query=query,
            caseSensitive=case_sensitive,
            isRegex=is_regex,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.SEARCH_IN_RESPONSE_BODY,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return SearchInResponseBodyResult.model_validate(result)

    async def set_blocked_u_r_ls(
        self,
        *,
        url_patterns: list[BlockPattern] | None = None,
        urls: list[str] | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetBlockedURLsParams(urlPatterns=url_patterns, urls=urls)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_BLOCKED_U_R_LS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_bypass_service_worker(
        self,
        *,
        bypass: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetBypassServiceWorkerParams(bypass=bypass)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_BYPASS_SERVICE_WORKER,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_cache_disabled(
        self,
        *,
        cache_disabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetCacheDisabledParams(cacheDisabled=cache_disabled)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_CACHE_DISABLED,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_cookie(
        self,
        *,
        name: str,
        value: str,
        url: str | None = None,
        domain: str | None = None,
        path: str | None = None,
        secure: bool | None = None,
        http_only: bool | None = None,
        same_site: CookieSameSite | None = None,
        expires: TimeSinceEpoch | None = None,
        priority: CookiePriority | None = None,
        same_party: bool | None = None,
        source_scheme: CookieSourceScheme | None = None,
        source_port: int | None = None,
        partition_key: CookiePartitionKey | None = None,
        session_id: str | None = None,
    ) -> SetCookieResult:
        params = SetCookieParams(
            name=name,
            value=value,
            url=url,
            domain=domain,
            path=path,
            secure=secure,
            httpOnly=http_only,
            sameSite=same_site,
            expires=expires,
            priority=priority,
            sameParty=same_party,
            sourceScheme=source_scheme,
            sourcePort=source_port,
            partitionKey=partition_key,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.SET_COOKIE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return SetCookieResult.model_validate(result)

    async def set_cookies(
        self,
        *,
        cookies: list[CookieParam],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetCookiesParams(cookies=cookies)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_COOKIES,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_extra_h_t_t_p_headers(
        self,
        *,
        headers: Headers,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetExtraHTTPHeadersParams(headers=headers)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_EXTRA_H_T_T_P_HEADERS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_attach_debug_stack(
        self,
        *,
        enabled: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetAttachDebugStackParams(enabled=enabled)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_ATTACH_DEBUG_STACK,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_request_interception(
        self,
        *,
        patterns: list[RequestPattern],
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetRequestInterceptionParams(patterns=patterns)

        result = await self._client.send_raw(
            method=NetworkCommand.SET_REQUEST_INTERCEPTION,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def set_user_agent_override(
        self,
        *,
        user_agent: str,
        accept_language: str | None = None,
        platform: str | None = None,
        user_agent_metadata: Emulation.UserAgentMetadata | None = None,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetUserAgentOverrideParams(
            userAgent=user_agent,
            acceptLanguage=accept_language,
            platform=platform,
            userAgentMetadata=user_agent_metadata,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.SET_USER_AGENT_OVERRIDE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def stream_resource_content(
        self,
        *,
        request_id: RequestId,
        session_id: str | None = None,
    ) -> StreamResourceContentResult:
        params = StreamResourceContentParams(requestId=request_id)

        result = await self._client.send_raw(
            method=NetworkCommand.STREAM_RESOURCE_CONTENT,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return StreamResourceContentResult.model_validate(result)

    async def get_security_isolation_status(
        self,
        *,
        frame_id: Page.FrameId | None = None,
        session_id: str | None = None,
    ) -> GetSecurityIsolationStatusResult:
        params = GetSecurityIsolationStatusParams(frameId=frame_id)

        result = await self._client.send_raw(
            method=NetworkCommand.GET_SECURITY_ISOLATION_STATUS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return GetSecurityIsolationStatusResult.model_validate(result)

    async def enable_reporting_api(
        self,
        *,
        enable: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableReportingApiParams(enable=enable)

        result = await self._client.send_raw(
            method=NetworkCommand.ENABLE_REPORTING_API,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def enable_device_bound_sessions(
        self,
        *,
        enable: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = EnableDeviceBoundSessionsParams(enable=enable)

        result = await self._client.send_raw(
            method=NetworkCommand.ENABLE_DEVICE_BOUND_SESSIONS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result

    async def fetch_schemeful_site(
        self,
        *,
        origin: str,
        session_id: str | None = None,
    ) -> FetchSchemefulSiteResult:
        params = FetchSchemefulSiteParams(origin=origin)

        result = await self._client.send_raw(
            method=NetworkCommand.FETCH_SCHEMEFUL_SITE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return FetchSchemefulSiteResult.model_validate(result)

    async def load_network_resource(
        self,
        *,
        frame_id: Page.FrameId | None = None,
        url: str,
        options: LoadNetworkResourceOptions,
        session_id: str | None = None,
    ) -> LoadNetworkResourceResult:
        params = LoadNetworkResourceParams(frameId=frame_id, url=url, options=options)

        result = await self._client.send_raw(
            method=NetworkCommand.LOAD_NETWORK_RESOURCE,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return LoadNetworkResourceResult.model_validate(result)

    async def set_cookie_controls(
        self,
        *,
        enable_third_party_cookie_restriction: bool,
        disable_third_party_cookie_metadata: bool,
        disable_third_party_cookie_heuristics: bool,
        session_id: str | None = None,
    ) -> dict[str, Any]:
        params = SetCookieControlsParams(
            enableThirdPartyCookieRestriction=enable_third_party_cookie_restriction,
            disableThirdPartyCookieMetadata=disable_third_party_cookie_metadata,
            disableThirdPartyCookieHeuristics=disable_third_party_cookie_heuristics,
        )

        result = await self._client.send_raw(
            method=NetworkCommand.SET_COOKIE_CONTROLS,
            params=params.to_cdp_params(),
            session_id=session_id,
        )
        return result
