# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import TYPE_CHECKING
from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *

from cdpify.domains import dom
from cdpify.domains import runtime


class DOMDebuggerCommand(StrEnum):
    GET_EVENT_LISTENERS = "DOMDebugger.getEventListeners"
    REMOVE_D_O_M_BREAKPOINT = "DOMDebugger.removeDOMBreakpoint"
    REMOVE_EVENT_LISTENER_BREAKPOINT = "DOMDebugger.removeEventListenerBreakpoint"
    REMOVE_INSTRUMENTATION_BREAKPOINT = "DOMDebugger.removeInstrumentationBreakpoint"
    REMOVE_X_H_R_BREAKPOINT = "DOMDebugger.removeXHRBreakpoint"
    SET_BREAK_ON_C_S_P_VIOLATION = "DOMDebugger.setBreakOnCSPViolation"
    SET_D_O_M_BREAKPOINT = "DOMDebugger.setDOMBreakpoint"
    SET_EVENT_LISTENER_BREAKPOINT = "DOMDebugger.setEventListenerBreakpoint"
    SET_INSTRUMENTATION_BREAKPOINT = "DOMDebugger.setInstrumentationBreakpoint"
    SET_X_H_R_BREAKPOINT = "DOMDebugger.setXHRBreakpoint"


class GetEventListenersParams(CDPModel):
    """
    Returns event listeners of the given object.
    """

    object_id: runtime.RemoteObjectId
    depth: int | None = None
    pierce: bool | None = None


class GetEventListenersResult(CDPModel):
    listeners: list[EventListener]


class RemoveDOMBreakpointParams(CDPModel):
    """
    Removes DOM breakpoint that was set using `setDOMBreakpoint`.
    """

    node_id: dom.NodeId
    type: DOMBreakpointType


class RemoveEventListenerBreakpointParams(CDPModel):
    """
    Removes breakpoint on particular DOM event.
    """

    event_name: str
    target_name: str | None = None


class RemoveInstrumentationBreakpointParams(CDPModel):
    """
    Removes breakpoint on particular native event.
    """

    event_name: str


class RemoveXHRBreakpointParams(CDPModel):
    """
    Removes breakpoint from XMLHttpRequest.
    """

    url: str


class SetBreakOnCSPViolationParams(CDPModel):
    """
    Sets breakpoint on particular CSP violations.
    """

    violation_types: list[CSPViolationType]


class SetDOMBreakpointParams(CDPModel):
    """
    Sets breakpoint on particular operation with DOM.
    """

    node_id: dom.NodeId
    type: DOMBreakpointType


class SetEventListenerBreakpointParams(CDPModel):
    """
    Sets breakpoint on particular DOM event.
    """

    event_name: str
    target_name: str | None = None


class SetInstrumentationBreakpointParams(CDPModel):
    """
    Sets breakpoint on particular native event.
    """

    event_name: str


class SetXHRBreakpointParams(CDPModel):
    """
    Sets breakpoint on XMLHttpRequest.
    """

    url: str
