# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *


class MemoryCommand(StrEnum):
    GET_D_O_M_COUNTERS = "Memory.getDOMCounters"
    GET_D_O_M_COUNTERS_FOR_LEAK_DETECTION = "Memory.getDOMCountersForLeakDetection"
    PREPARE_FOR_LEAK_DETECTION = "Memory.prepareForLeakDetection"
    FORCIBLY_PURGE_JAVA_SCRIPT_MEMORY = "Memory.forciblyPurgeJavaScriptMemory"
    SET_PRESSURE_NOTIFICATIONS_SUPPRESSED = "Memory.setPressureNotificationsSuppressed"
    SIMULATE_PRESSURE_NOTIFICATION = "Memory.simulatePressureNotification"
    START_SAMPLING = "Memory.startSampling"
    STOP_SAMPLING = "Memory.stopSampling"
    GET_ALL_TIME_SAMPLING_PROFILE = "Memory.getAllTimeSamplingProfile"
    GET_BROWSER_SAMPLING_PROFILE = "Memory.getBrowserSamplingProfile"
    GET_SAMPLING_PROFILE = "Memory.getSamplingProfile"


class GetDOMCountersResult(CDPModel):
    documents: int
    nodes: int
    js_event_listeners: int


class GetDOMCountersForLeakDetectionResult(CDPModel):
    counters: list[DOMCounter]


class SetPressureNotificationsSuppressedParams(CDPModel):
    """
    Enable/disable suppressing memory pressure notifications in all processes.
    """

    suppressed: bool


class SimulatePressureNotificationParams(CDPModel):
    """
    Simulate a memory pressure notification in all processes.
    """

    level: PressureLevel


class StartSamplingParams(CDPModel):
    """
    Start collecting native memory profile.
    """

    sampling_interval: int | None = None
    suppress_randomness: bool | None = None


class GetAllTimeSamplingProfileResult(CDPModel):
    profile: SamplingProfile


class GetBrowserSamplingProfileResult(CDPModel):
    profile: SamplingProfile


class GetSamplingProfileResult(CDPModel):
    profile: SamplingProfile
