# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from typing import TYPE_CHECKING
from enum import StrEnum
from cdpify.domains.base import CDPModel

from .types import *

from cdpify.domains import runtime


class IOCommand(StrEnum):
    CLOSE = "IO.close"
    READ = "IO.read"
    RESOLVE_BLOB = "IO.resolveBlob"


class CloseParams(CDPModel):
    """
    Close the stream, discard any temporary backing storage.
    """

    handle: StreamHandle


class ReadParams(CDPModel):
    """
    Read a chunk of the stream
    """

    handle: StreamHandle
    offset: int | None = None
    size: int | None = None


class ReadResult(CDPModel):
    base64_encoded: bool | None = None
    data: str
    eof: bool


class ResolveBlobParams(CDPModel):
    """
    Return UUID of Blob object specified by a remote object id.
    """

    object_id: runtime.RemoteObjectId


class ResolveBlobResult(CDPModel):
    uuid: str
